#!/usr/bin/python

from mininet.net import Mininet
from mininet.topolib import TreeTopo
from mininet.topo import Topo
from mininet.log import setLogLevel
from mininet.cli import CLI
from mininet.term import cleanUpScreens,makeTerm
from subprocess import Popen
import os 
import subprocess


class MinimalTopo(Topo):
	"Creamos una topologia minima con un switch y 2 hosts"

	def build (self):
		#Creamos los dos host
		h1 = self.addHost('h1')
		h2 = self.addHost('h2')

		# Creamos los switchs
		s1 = self.addSwitch('s1')

		#Annado los enlaces (recuerda si quieres annadir algo TCPLink)
		self.addLink(s1,h1)
		self.addLink(s1,h2)

def runMinimalTopo():
	#VAmos a lanzar mininet con un topologia minima

	topo = MinimalTopo()

	net = Mininet(topo=topo);

	# Empezamos la topologia
	net.start()


	net.pingAll()

	h1,h2=net.get('h1','h2')
	##AQUI VAMOS A EMPEZAR A PROBAR COSAS

	print h1.cmd('ping -c1', h2.IP())
	

	#Esto sirve para lanzar un temrinal
	cmd = 'su -c vlc bayesiansdn "/home/bayesiansdn/bayesiansdn-demos/network-simulator/mininet/net/samples/small.mp4"'
	clienteh1=makeTerm(h1, title='VLC server', term='xterm', display=None, cmd=cmd)

	

	#CLI(net)

	#net.stop()

if __name__ == '__main__':
	#esto sirve para exportar las funciones, sin que se ejecute
	setLogLevel('info')
	runMinimalTopo()


