#=========================== Filebeat prospectors =============================

filebeat.prospectors:

- input_type: log
  enabled: true
  paths:
    - /home/bayes/Repositories/pruebas/logs/c*.log
  document_type: vlc_client

- input_type: log
  enabled: true
  paths:
    - /home/bayes/Repositories/pruebas/logs/s*.log
  document_type: vlc_server

- input_type: log
  enabled: true
  paths:
    - /home/bayes/Repositories/pruebas/infoSession/infosessionC*.log
  document_type: infosession_client

- input_type: log
  enabled: true
  paths:
    - /home/bayes/Repositories/pruebas/infoSession/infosessionS*.log
  document_type: infosession_server

#----------------------------- Logstash output --------------------------------
output.logstash:
  # The Logstash hosts
  hosts: ["localhost:5044"]