#=========================== Filebeat prospectors =============================

filebeat.prospectors:

- input_type: log
  paths:
    - /home/bayes/Repositories/pruebas/logs/c*.log
  #fields:
    #vlc_client: true #adding a field called vlc_client to the messages
  document_type: vlc_client

- input_type: log
  paths:
    - /home/bayes/Repositories/pruebas/logs/s*.log
  document_type: vlc_server

- input_type: log
  paths:
     - /home/bayes/Repositories/pruebas/infoSession/*.log
  document_type: info_session

#================================ Outputs =====================================
#-------------------------- Elasticsearch output ------------------------------
# output.elasticsearch:
  # Array of hosts to connect to.
  # hosts: ["localhost:9200"]

#----------------------------- Logstash output --------------------------------
output.logstash:
  # The Logstash hosts
  hosts: ["localhost:5044"]

  # Optional SSL. By default is off.
  # List of root certificates for HTTPS server verifications
  #ssl.certificate_authorities: ["/etc/pki/root/ca.pem"]

  # Certificate for SSL client authentication
  #ssl.certificate: "/etc/pki/client/cert.pem"

  # Client Certificate Key
  #ssl.key: "/etc/pki/client/cert.key"
